apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasher
  labels:
    app: hasher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasher
  template:
    metadata:
      labels:
        app: hasher
    spec:
      containers:
      - name: hasher
        image: dockercoins/hasher:v0.1
---
apiVersion: v1
kind: Service
metadata:
  name: hasher
  labels:
    app: hasher
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: hasher