apiVersion: apps/v1
kind: Deployment
metadata:
  name: rng
  labels:
    app: rng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rng
  template:
    metadata:
      labels:
        app: rng
    spec:
      containers:
      - name: rng
        image: dockercoins/rng:v0.1
---
apiVersion: v1
kind: Service
metadata:
  name: rng
  labels:
    app: rng
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: rng