apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-volume
spec:
  volumes: 
  - name: www # crea un volumen con el nombre www
  containers:
  - name: nginx # contenedor de nginx
    image: nginx
    volumeMounts:
    - name: www # nombre del volumen - es el mismo volumen que usa git
      mountPath: /usr/share/nginx/html/ # ruta donde se montara el volumen
  - name: git # contenedor de git
    image: alpine
    command: [ "sh", "-c", "apk add --no-cache git && git clone https://github.com/octocat/Spoon-Knife /www" ] # clona un repositorio en una carpeta /www - es donde esta el volumen www
    volumeMounts:
    - name: www # nombre del volumen
      mountPath: /www/  # ruta donde se montara el volumen /www/
  restartPolicy: OnFailure # si falla el contenedor se reinicia, solo si falla, asi evitamos que si termina bien se este reiniciando constantemente
