apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"hasher"},"name":"hasher","namespace":"default"},"spec":{"ports":[{"port":80,"protocol":"TCP"}],"selector":{"app":"hasher"}}}
  creationTimestamp: "2021-09-08T03:15:16Z"
  labels:
    app: hasher
  name: hasher
  namespace: default
  resourceVersion: "11228"
  uid: df937281-87c9-47fd-afab-145f4196513f
spec:
  clusterIP: 172.20.216.89
  clusterIPs:
  - 172.20.216.89
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hasher
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
