apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"webui"},"name":"webui","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"webui"}},"template":{"metadata":{"labels":{"app":"webui"}},"spec":{"containers":[{"image":"dockercoins/webui:v0.1","name":"webui"}]}}}}
  creationTimestamp: "2021-09-08T03:15:35Z"
  generation: 1
  labels:
    app: webui
  name: webui
  namespace: default
  resourceVersion: "11395"
  uid: 51cbe692-4239-4500-bdf0-71fbbd164467
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: webui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webui
    spec:
      containers:
      - image: dockercoins/webui:v0.1
        imagePullPolicy: IfNotPresent
        name: webui
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-09-08T03:15:47Z"
    lastUpdateTime: "2021-09-08T03:15:47Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-09-08T03:15:35Z"
    lastUpdateTime: "2021-09-08T03:15:47Z"
    message: ReplicaSet "webui-5f69bbf966" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
