apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"webui"},"name":"webui","namespace":"default"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP"}],"selector":{"app":"webui"},"type":"NodePort"}}
  creationTimestamp: "2021-09-08T03:15:35Z"
  labels:
    app: webui
  name: webui
  namespace: default
  resourceVersion: "11342"
  uid: ecccf676-f9b1-46f5-8a95-5e63f8f26de0
spec:
  clusterIP: 172.20.84.23
  clusterIPs:
  - 172.20.84.23
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30461
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webui
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
